swagger: '2.0'
info:
  version: 1.0.0
  title: POC Login qqq
  description: <img src="https://themessaging.co/wp-content/uploads/2023/11/TMC_Logo_FC_RGB_Pos.png" alt="POC image"><img src="https://miro.medium.com/v2/resize:fit:250/1*c6vKgd_P1AhBcmmW9aMaGA.jpeg" alt="POC hacked"><br> Login to continue services below or go to https://arif.com
host: muslimsec.com
basePath: /tmsg/
paths:
 /Login_Page.php:
    post:
      summary: Login here to continue
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
          - name: submit
          in: formData
          description: The username for login
          default: SAVE
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters.
        '500':
          description: Internal server error.
